name: 'Create Windows Folder With Permissions'

description: 'This action will create a folder, including any nested folders. This will not remove items from the folder.'

inputs:
  server:
    description: 'The name of the target server'
    required: true
  folder-path:
    description: 'The entire path to the folder'
    required: true
  read-users:
    description: 'Comma separated list of users for Read access'
    default: ''
    required: false
  write-users:
    description: 'Comma separated list of users for Write access'
    default: ''
    required: false
  modify-users:
    description: 'Comma separated list of users for Modify access'
    default: ''
    required: false
  deployment-service-account-id:
    description: 'The service account id used to run script'
    required: true
  deployment-service-account-secret:
    description: 'The service account secret used to run script'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $deployment_password_string = @'
        ${{ inputs.deployment-service-account-secret }}
        '@
        $secure_deployment_password = ConvertTo-SecureString -String $deployment_password_string -AsPlainText -Force

        ${{ github.action_path }}/folder_action.ps1 `
          -server '${{ inputs.server }}' `
          -folder_path '${{ inputs.folder-path }}' `
          -read_users '${{ inputs.read-users }}' `
          -write_users '${{ inputs.write-users }}' `
          -modify_users '${{ inputs.modify-users }}' `
          -deploy_user_id '${{ inputs.deployment-service-account-id }}' `
          -deploy_user_secret $secure_deployment_password
